{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mdqhz7oy3zeyzbzfqzf3hnchue"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.37"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.7.2-SNAPSHOT.aar",
          "url": "deepsdk-0.7.2-SNAPSHOT.aar",
          "size": 41361785,
          "sha512": "8338e5bfed56d794aae1499c52c9cc8fbf7ae1ade850a3d729f5bdede1abbfa901d250d87459eb68d625228dd5cfb3fd6363f33c8b6231be373784cb2790a56e",
          "sha256": "77cd245ffc18ec2af4fe98da6f7fc806166ecd179487faacd8ae7e04c7d62d8e",
          "sha1": "7f1616fa689ff6da3745eeb16242cd7c045ce6ff",
          "md5": "4a6c7f7b85362e4bac15b5ebff48a5a2"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.37"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.7.2-SNAPSHOT.aar",
          "url": "deepsdk-0.7.2-SNAPSHOT.aar",
          "size": 41361785,
          "sha512": "8338e5bfed56d794aae1499c52c9cc8fbf7ae1ade850a3d729f5bdede1abbfa901d250d87459eb68d625228dd5cfb3fd6363f33c8b6231be373784cb2790a56e",
          "sha256": "77cd245ffc18ec2af4fe98da6f7fc806166ecd179487faacd8ae7e04c7d62d8e",
          "sha1": "7f1616fa689ff6da3745eeb16242cd7c045ce6ff",
          "md5": "4a6c7f7b85362e4bac15b5ebff48a5a2"
        }
      ]
    }
  ]
}
