{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.5.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "2s6ibihpizhw5j5hnlkfobfsxi"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.6-SNAPSHOT.aar",
          "url": "deepsdk-0.5.6-SNAPSHOT.aar",
          "size": 19573214,
          "sha512": "63df6b7dfe81e597f86ce84af773c47455de738458d6550f2e678f828a9610b683e639b481c939629b95fc5cc87b54657114946a2d19ea5a17f5f0a267b3c269",
          "sha256": "b2bc5956cc203f9f251764209e7e461ac2c8445c75afe04aa594083694e41071",
          "sha1": "c55d0bd70f7d70cf1568cbca8a76ca97b11980aa",
          "md5": "10231ea9175b51d2880bb6cc94a567a3"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.6-SNAPSHOT.aar",
          "url": "deepsdk-0.5.6-SNAPSHOT.aar",
          "size": 19573214,
          "sha512": "63df6b7dfe81e597f86ce84af773c47455de738458d6550f2e678f828a9610b683e639b481c939629b95fc5cc87b54657114946a2d19ea5a17f5f0a267b3c269",
          "sha256": "b2bc5956cc203f9f251764209e7e461ac2c8445c75afe04aa594083694e41071",
          "sha1": "c55d0bd70f7d70cf1568cbca8a76ca97b11980aa",
          "md5": "10231ea9175b51d2880bb6cc94a567a3"
        }
      ]
    }
  ]
}
