{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ivvutgny6bgzjhfsfuyhbkbuva"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.0-SNAPSHOT.aar",
          "url": "deepsdk-0.5.0-SNAPSHOT.aar",
          "size": 19529014,
          "sha512": "cbd159ef00f3b5146804d754ee39a8471d1e80882c086f788e14f983a89d23e2eeea56f3e4bdeffae0d3b21ecc0cc3f6143b3764c465c696b09d3dcdc12fdd80",
          "sha256": "86b19e0f2f4248b0cc07de2db5d271f6884e5c5a0e679b9717d810ad7fe625db",
          "sha1": "4b82d931ca35afdae9fd3b3d740f40a2d8f4cbe0",
          "md5": "fe2b8dbf16d1abe4439dd19e998560b4"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.0-SNAPSHOT.aar",
          "url": "deepsdk-0.5.0-SNAPSHOT.aar",
          "size": 19529014,
          "sha512": "cbd159ef00f3b5146804d754ee39a8471d1e80882c086f788e14f983a89d23e2eeea56f3e4bdeffae0d3b21ecc0cc3f6143b3764c465c696b09d3dcdc12fdd80",
          "sha256": "86b19e0f2f4248b0cc07de2db5d271f6884e5c5a0e679b9717d810ad7fe625db",
          "sha1": "4b82d931ca35afdae9fd3b3d740f40a2d8f4cbe0",
          "md5": "fe2b8dbf16d1abe4439dd19e998560b4"
        }
      ]
    }
  ]
}
