{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.4.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "asokxnnuazf3hp35gsfjolpwqm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.2-SNAPSHOT.aar",
          "url": "deepsdk-0.4.2-SNAPSHOT.aar",
          "size": 998397,
          "sha512": "5205357d4e1bb9171767ec8b12b5a44d0002fbca0f2c060141f3d8779625f884ead57e64f6056809200eeb78c9902dd87de76796ca8abe55a9779c81b98024a5",
          "sha256": "e9993d4adee0fbcb4911eac8c484272e4bf22c3d82c35defbf5776ab2c7194ef",
          "sha1": "d683f6cdad36eb6323207f1d512903087bc21dc8",
          "md5": "8b2638722cb7fcd05333bde4948ad7a0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.2-SNAPSHOT.aar",
          "url": "deepsdk-0.4.2-SNAPSHOT.aar",
          "size": 998397,
          "sha512": "5205357d4e1bb9171767ec8b12b5a44d0002fbca0f2c060141f3d8779625f884ead57e64f6056809200eeb78c9902dd87de76796ca8abe55a9779c81b98024a5",
          "sha256": "e9993d4adee0fbcb4911eac8c484272e4bf22c3d82c35defbf5776ab2c7194ef",
          "sha1": "d683f6cdad36eb6323207f1d512903087bc21dc8",
          "md5": "8b2638722cb7fcd05333bde4948ad7a0"
        }
      ]
    }
  ]
}
