{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "s435rwsrfva6pd765whgw3pg5i"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.37"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.7.0-SNAPSHOT.aar",
          "url": "deepsdk-0.7.0-SNAPSHOT.aar",
          "size": 41346443,
          "sha512": "f246fbd9a2a0a4fd80bfd7e1591d66625d2781dde27b0ae139cc7681ea196102fffba67e3930dfdc4ffffc6f6aa6933cf75462efdfef46d30100938eff7da772",
          "sha256": "7b86a3fbfb1d5b3bad6174254116d07e489ed851a3b72e8da59a2bca2e552948",
          "sha1": "1ffa03be290ff10272c0268a3e71c7f5f82a95b9",
          "md5": "e1177eceef3dc5b8ac57f5b5f4b37ac3"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.37"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.7.0-SNAPSHOT.aar",
          "url": "deepsdk-0.7.0-SNAPSHOT.aar",
          "size": 41346443,
          "sha512": "f246fbd9a2a0a4fd80bfd7e1591d66625d2781dde27b0ae139cc7681ea196102fffba67e3930dfdc4ffffc6f6aa6933cf75462efdfef46d30100938eff7da772",
          "sha256": "7b86a3fbfb1d5b3bad6174254116d07e489ed851a3b72e8da59a2bca2e552948",
          "sha1": "1ffa03be290ff10272c0268a3e71c7f5f82a95b9",
          "md5": "e1177eceef3dc5b8ac57f5b5f4b37ac3"
        }
      ]
    }
  ]
}
