{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3hm4avymkff7zbj5untryqjciu"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.6.0-SNAPSHOT.aar",
          "url": "deepsdk-0.6.0-SNAPSHOT.aar",
          "size": 19578598,
          "sha512": "6e9d9f83408fc22f804f17e91f3d9b35da965d5e2ed17f98dbb37463cd96328bb23b7b754e387ee834c7882840e60608c503f72f2d74d754af6693e1fd867a7c",
          "sha256": "edc89cc82ce91a3930e703c5d974a0b24d1ab5b262e351d90a35a4f74cb464c9",
          "sha1": "d96a20175c35a699762cbd3acf3bc2a5e58980b0",
          "md5": "b421344f13fcfde11d03bd34f6ab4155"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.6.0-SNAPSHOT.aar",
          "url": "deepsdk-0.6.0-SNAPSHOT.aar",
          "size": 19578598,
          "sha512": "6e9d9f83408fc22f804f17e91f3d9b35da965d5e2ed17f98dbb37463cd96328bb23b7b754e387ee834c7882840e60608c503f72f2d74d754af6693e1fd867a7c",
          "sha256": "edc89cc82ce91a3930e703c5d974a0b24d1ab5b262e351d90a35a4f74cb464c9",
          "sha1": "d96a20175c35a699762cbd3acf3bc2a5e58980b0",
          "md5": "b421344f13fcfde11d03bd34f6ab4155"
        }
      ]
    }
  ]
}
