{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.4.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "awz2lbhyo5axpbgi6dmo442t44"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.3-SNAPSHOT.aar",
          "url": "deepsdk-0.4.3-SNAPSHOT.aar",
          "size": 989066,
          "sha512": "63c0caf22d4b893f7f72f7ba89eb3e78e1162b4d6fdfc8845764eabf255a8a302c4d2dd0676af2cee642c0e396393887575119e03a9495ce00754b4f294a9b66",
          "sha256": "8c30cb41e504626b55b77720a459768c9d8f72f2e25bfb269443d96dfd1f6ac3",
          "sha1": "4527c25f846e1ee988dc48d58ca58687a2663b37",
          "md5": "02404103191337868bd9b298f80a8268"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.3-SNAPSHOT.aar",
          "url": "deepsdk-0.4.3-SNAPSHOT.aar",
          "size": 989066,
          "sha512": "63c0caf22d4b893f7f72f7ba89eb3e78e1162b4d6fdfc8845764eabf255a8a302c4d2dd0676af2cee642c0e396393887575119e03a9495ce00754b4f294a9b66",
          "sha256": "8c30cb41e504626b55b77720a459768c9d8f72f2e25bfb269443d96dfd1f6ac3",
          "sha1": "4527c25f846e1ee988dc48d58ca58687a2663b37",
          "md5": "02404103191337868bd9b298f80a8268"
        }
      ]
    }
  ]
}
