{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.5.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bntb5sgdnvaxfi5wx3ts4vg7gq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.4-SNAPSHOT.aar",
          "url": "deepsdk-0.5.4-SNAPSHOT.aar",
          "size": 19561751,
          "sha512": "82a273498bfa7da01e2a8b4a299f2e26f2b856cc54b0656217c901deeed8cc4637381ec57b6bbee85b82d55a9653b341290e6a4e88b7528a53bf5710049c6e2a",
          "sha256": "88ae98c543e77401141d082b7179815db97076f99228df4110c50fabdf636abe",
          "sha1": "9300a3807e651fcbc642aec969f76bf05589a435",
          "md5": "cbc92001174709d4c4a040d6bdaa77a1"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.4-SNAPSHOT.aar",
          "url": "deepsdk-0.5.4-SNAPSHOT.aar",
          "size": 19561751,
          "sha512": "82a273498bfa7da01e2a8b4a299f2e26f2b856cc54b0656217c901deeed8cc4637381ec57b6bbee85b82d55a9653b341290e6a4e88b7528a53bf5710049c6e2a",
          "sha256": "88ae98c543e77401141d082b7179815db97076f99228df4110c50fabdf636abe",
          "sha1": "9300a3807e651fcbc642aec969f76bf05589a435",
          "md5": "cbc92001174709d4c4a040d6bdaa77a1"
        }
      ]
    }
  ]
}
