{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.4.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ru4emzkutvfb7g6dbjf3csboeq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.4-SNAPSHOT.aar",
          "url": "deepsdk-0.4.4-SNAPSHOT.aar",
          "size": 989517,
          "sha512": "979309d9f87a2ab7537893c3ba23160e1af659733e3bb1ca08b4968ac1538a2f576084f7588b6e7cb2cbed3a23ef456d3de20350620e28edc87b78aea7679e8e",
          "sha256": "f0bd5dc1c5cded079b5ea9c5d548f2694bf6fce48b6324ab065f019151c277c6",
          "sha1": "143e0349b660c01efc64051cb46316e26fd2a515",
          "md5": "d5b8cdb195b3014f1d50554e9587927c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.4-SNAPSHOT.aar",
          "url": "deepsdk-0.4.4-SNAPSHOT.aar",
          "size": 989517,
          "sha512": "979309d9f87a2ab7537893c3ba23160e1af659733e3bb1ca08b4968ac1538a2f576084f7588b6e7cb2cbed3a23ef456d3de20350620e28edc87b78aea7679e8e",
          "sha256": "f0bd5dc1c5cded079b5ea9c5d548f2694bf6fce48b6324ab065f019151c277c6",
          "sha1": "143e0349b660c01efc64051cb46316e26fd2a515",
          "md5": "d5b8cdb195b3014f1d50554e9587927c"
        }
      ]
    }
  ]
}
