{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o7uybr2xz5aljey5qccecd4xrq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.2.aar",
          "url": "deepsdk-0.5.2.aar",
          "size": 19431824,
          "sha512": "ef42023ad272b59dccdce74fcac9dcd2f6f00f470568c82abc08b5e37695d444ca05433b701f67f88c3558f0cc0f8f31ef82c28c4c1ab6d6227f47792b2fb8cd",
          "sha256": "2984d910cb49a1d8db58c73dafe1e2bc0e5fb724b2b227a72bfc382fe797e9bb",
          "sha1": "9b01f44437284320d9dd5f945e308fab2f77d669",
          "md5": "a572fc4e36049d02057da3c44c14b69e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.2.aar",
          "url": "deepsdk-0.5.2.aar",
          "size": 19431824,
          "sha512": "ef42023ad272b59dccdce74fcac9dcd2f6f00f470568c82abc08b5e37695d444ca05433b701f67f88c3558f0cc0f8f31ef82c28c4c1ab6d6227f47792b2fb8cd",
          "sha256": "2984d910cb49a1d8db58c73dafe1e2bc0e5fb724b2b227a72bfc382fe797e9bb",
          "sha1": "9b01f44437284320d9dd5f945e308fab2f77d669",
          "md5": "a572fc4e36049d02057da3c44c14b69e"
        }
      ]
    }
  ]
}
