{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "st4wllxohjfothivmdajzbitse"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.0-SNAPSHOT.aar",
          "url": "deepsdk-0.4.0-SNAPSHOT.aar",
          "size": 980802,
          "sha512": "64998aae8dcc7fea2f0b79c929e6e0032d6939c131b40f14bc1414fa4b7fdef19dbe049d5ee4e971890f4cebe8848919a55e6f462575409803333cf6039a97b0",
          "sha256": "2b5294029a456ec1f77972784af40a06e3d37a06883d456d257848fa6fbe10ee",
          "sha1": "be7f891c1b35d22bbe16fa11e44cb396729d6e6e",
          "md5": "ee98bf3551c0aa1c08abf0236d3e5cdf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.0-SNAPSHOT.aar",
          "url": "deepsdk-0.4.0-SNAPSHOT.aar",
          "size": 980802,
          "sha512": "64998aae8dcc7fea2f0b79c929e6e0032d6939c131b40f14bc1414fa4b7fdef19dbe049d5ee4e971890f4cebe8848919a55e6f462575409803333cf6039a97b0",
          "sha256": "2b5294029a456ec1f77972784af40a06e3d37a06883d456d257848fa6fbe10ee",
          "sha1": "be7f891c1b35d22bbe16fa11e44cb396729d6e6e",
          "md5": "ee98bf3551c0aa1c08abf0236d3e5cdf"
        }
      ]
    }
  ]
}
