{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.5.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "tqjbd7qtdjecvcr3rkaig4zgfq"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.3-SNAPSHOT.aar",
          "url": "deepsdk-0.5.3-SNAPSHOT.aar",
          "size": 19561187,
          "sha512": "7fce438e48477d599abfde216d04d04aa3a4f82eea7ab0c3a62494f2879a236e731f817589e13ba5b720d4d26b772f238a52c8dfdcc9b4e65ecc8d0b06a7ccd1",
          "sha256": "0063b1ac3b556baf0806c8a32941b1a432fddf91fad943023e92858f875a5cfd",
          "sha1": "793f348161d593765d1c1ea6edf550209898fe4e",
          "md5": "3d823ecb2e3dbb0fb54e94d01c1d9e6d"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.3-SNAPSHOT.aar",
          "url": "deepsdk-0.5.3-SNAPSHOT.aar",
          "size": 19561187,
          "sha512": "7fce438e48477d599abfde216d04d04aa3a4f82eea7ab0c3a62494f2879a236e731f817589e13ba5b720d4d26b772f238a52c8dfdcc9b4e65ecc8d0b06a7ccd1",
          "sha256": "0063b1ac3b556baf0806c8a32941b1a432fddf91fad943023e92858f875a5cfd",
          "sha1": "793f348161d593765d1c1ea6edf550209898fe4e",
          "md5": "3d823ecb2e3dbb0fb54e94d01c1d9e6d"
        }
      ]
    }
  ]
}
