{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ivvutgny6bgzjhfsfuyhbkbuva"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.0.aar",
          "url": "deepsdk-0.5.0.aar",
          "size": 19408263,
          "sha512": "d2ce256799d7dc5c689288797586519781f9f55727697d03a983105d975f22b614c6d8018241398a2861fd3553e1d01bbf820ba8c177dd74063bee4767064a74",
          "sha256": "8881ff6e3dccce83a3bd390d10e5bf45c9428bab11c7b157c9ba30f42e878807",
          "sha1": "7b661555806b4b2d8ba8ed2022a6b20fa03453e3",
          "md5": "fa5ea32a3106a76642b82f1660561d9d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.5.0.aar",
          "url": "deepsdk-0.5.0.aar",
          "size": 19408263,
          "sha512": "d2ce256799d7dc5c689288797586519781f9f55727697d03a983105d975f22b614c6d8018241398a2861fd3553e1d01bbf820ba8c177dd74063bee4767064a74",
          "sha256": "8881ff6e3dccce83a3bd390d10e5bf45c9428bab11c7b157c9ba30f42e878807",
          "sha1": "7b661555806b4b2d8ba8ed2022a6b20fa03453e3",
          "md5": "fa5ea32a3106a76642b82f1660561d9d"
        }
      ]
    }
  ]
}
