{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "t2kr2jwm5vaglflic2clsrfire"
    }
  },
  "variants": [
    {
      "name": "debugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.37"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.7.1-SNAPSHOT.aar",
          "url": "deepsdk-0.7.1-SNAPSHOT.aar",
          "size": 41361780,
          "sha512": "9d574bf3e52a4f7e79b74c4660514c4b87bc8ac72f7ae0e09216a9ca0035b475cba43d064a53223b018c1b0e6281a83083b3dc99ba78e55d9b657650ce4b726c",
          "sha256": "419100c577410a898de049988d80859fd5cc3ee1022b752ac6592fba78faf3a3",
          "sha1": "92e2760ec41fe88a0d83d337ee4e1600dd994f61",
          "md5": "91c1f6959d16a99592d08a71acbdb5d7"
        }
      ]
    },
    {
      "name": "debugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.37"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.1.1"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.7.1-SNAPSHOT.aar",
          "url": "deepsdk-0.7.1-SNAPSHOT.aar",
          "size": 41361780,
          "sha512": "9d574bf3e52a4f7e79b74c4660514c4b87bc8ac72f7ae0e09216a9ca0035b475cba43d064a53223b018c1b0e6281a83083b3dc99ba78e55d9b657650ce4b726c",
          "sha256": "419100c577410a898de049988d80859fd5cc3ee1022b752ac6592fba78faf3a3",
          "sha1": "92e2760ec41fe88a0d83d337ee4e1600dd994f61",
          "md5": "91c1f6959d16a99592d08a71acbdb5d7"
        }
      ]
    }
  ]
}
