{
  "formatVersion": "1.1",
  "component": {
    "group": "com.deepmirror",
    "module": "deepsdk",
    "version": "0.4.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jfqgwww7w5c7nmqtnzzoanxsy4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.1-SNAPSHOT.aar",
          "url": "deepsdk-0.4.1-SNAPSHOT.aar",
          "size": 998409,
          "sha512": "4ab1d8d0006fcea800e40b062d0a784ccdcf41270b40b2d86a034b81bdda66b55fc030b02daa7b584e5f0ada20e686b774a5e10b31d109e786b6529176f6d366",
          "sha256": "40b0709744f3f5976da01c6a968260cfe1d4ad508a170ead0b5d55994f89ff49",
          "sha1": "61af0267530c8a28c068f08a6aa5d0f6ad4cf9ca",
          "md5": "21b41563ac63437a432388cccb0a413d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "org.boofcv",
          "module": "boofcv-core",
          "version": {
            "requires": "0.35"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.apache.commons",
              "module": "commons-compress"
            },
            {
              "group": "com.thoughtworks.xstream",
              "module": "commons-compress"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "deepsdk-0.4.1-SNAPSHOT.aar",
          "url": "deepsdk-0.4.1-SNAPSHOT.aar",
          "size": 998409,
          "sha512": "4ab1d8d0006fcea800e40b062d0a784ccdcf41270b40b2d86a034b81bdda66b55fc030b02daa7b584e5f0ada20e686b774a5e10b31d109e786b6529176f6d366",
          "sha256": "40b0709744f3f5976da01c6a968260cfe1d4ad508a170ead0b5d55994f89ff49",
          "sha1": "61af0267530c8a28c068f08a6aa5d0f6ad4cf9ca",
          "md5": "21b41563ac63437a432388cccb0a413d"
        }
      ]
    }
  ]
}
